apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-letsencrypt-production
  labels:
    ca: letsencrypt
    environment: production
    solver: http01
spec:
  acme:
    {{- if .Values.email }}
    email: {{ .Values.email }}
    {{- end }}
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: cert-manager-letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingressClass }}
